package com.shopping.url.parse;


public class MyntraUrls {


    public static String [] urls = {
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-slim-fit-jeans/252354/buy?src=search&uq=&searchQuery=men-jeans&serp=1",
            "http://www.myntra.com/shirts/mark-taylor/mark-taylor-men-white--pink-checked-slim-fit-formal-shirt/289354/buy?src=search&uq=&searchQuery=men-formal-shirts&serp=1",
            "http://www.myntra.com/tops/faballey/faballey-women-red-top/247823/buy?src=search&uq=&searchQuery=women-tops-tees&serp=10",
            "http://www.myntra.com/dresses/the-vanca/the-vanca-navy-polka-dot-print-fit--flare-dress/237462/buy?src=search&uq=&searchQuery=women-dresses&serp=15",
            "http://www.myntra.com/heels/blue-button/blue-button-women-blue-pumps/247403/buy?src=search",
            "http://www.myntra.com/watches/police/police-women-white-dial-watch/143070/buy?src=search",
            "http://www.myntra.com/trousers/roadster/roadster-men-khaki-brent-slim-fit-chino-trousers/253311/buy?src=search"
    };

    public static String [] all_urls = {
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-slim-fit-jeans/252354/buy?src=search&uq=&searchQuery=men-jeans&serp=1",
            "http://www.myntra.com/shirts/mark-taylor/mark-taylor-men-white--pink-checked-slim-fit-formal-shirt/289354/buy?src=search&uq=&searchQuery=men-formal-shirts&serp=1",
            "http://www.myntra.com/tops/faballey/faballey-women-red-top/247823/buy?src=search&uq=&searchQuery=women-tops-tees&serp=10",
            "http://www.myntra.com/dresses/the-vanca/the-vanca-navy-polka-dot-print-fit--flare-dress/237462/buy?src=search&uq=&searchQuery=women-dresses&serp=15",
            "http://www.myntra.com/heels/blue-button/blue-button-women-blue-pumps/247403/buy?src=search",
            "http://www.myntra.com/watches/police/police-women-white-dial-watch/143070/buy?src=search",
            "http://www.myntra.com/trousers/roadster/roadster-men-khaki-brent-slim-fit-chino-trousers/253311/buy?src=search",
            "http://www.myntra.com/trousers/roadster/roadster-men-grey-torino-slim-fit-chino-trousers/253312/buy?src=search",
            "http://www.myntra.com/shirts/us-polo-assn/us-polo-assn-men-navy-tailored-fit-casual-shirt/234607/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-slim-fit-jeans/252354/buy?src=search",
            "http://www.myntra.com/shirts/hrx/hrx-men-white--green-checked-casual-shirt/259762/buy?src=search",
            "http://www.myntra.com/track-pants/kook-n-keech-disney/kook-n-keech-disney-men-navy-track-pants/273288/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-corvette-slim-fit-jeans/248892/buy?src=search",
            "http://www.myntra.com/trousers/mast--harbour/mast--harbour-men-beige-trousers/211963/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-navy-jeans/252353/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-blue-t-shirt/267637/buy?src=search",
            "http://www.myntra.com/track-pants/adidas/adidas-men-navy-track-pants/281264/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-blue-t-shirt/267541/buy?src=search",
            "http://www.myntra.com/tshirts/dc-comics/dc-comics-men-red-sleeveless-printed-t-shirt/315412/buy?src=search",
            "http://www.myntra.com/jeans/lee/lee-men-blue-low-bruce-skinny-fit-jeans/310241/buy?src=search",
            "http://www.myntra.com/shirts/dazzio/dazzio-men-blue-slim-fit-casual-shirt/297612/buy?src=search",
            "http://www.myntra.com/shirts/lee-cooper/lee-cooper-men-red-slim-fit-casual-shirt/331518/buy?src=search",
            "http://www.myntra.com/shorts/roadster/roadster-men-black-checked-shorts/253303/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-grey-t-shirt/267612/buy?src=search",
            "http://www.myntra.com/jeans/wrangler/wrangler-men-blue-millard-slim-fit-jeans/256922/buy?src=search",
            "http://www.myntra.com/tshirts/hrx/hrx-men-grey-t-shirt/287178/buy?src=search",
            "http://www.myntra.com/trousers/derby/derby-men-brown-slim-fit-casual-trousers/264182/buy?src=search",
            "http://www.myntra.com/shirts/roadster/roadster-men-white-vettel-shelby-slim-fit-casual-shirt/262364/buy?src=search",
            "http://www.myntra.com/jackets/even/even-men-black-slim-fit-nehru-jacket/324430/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-blue-t-shirt/267627/buy?src=search",
            "http://www.myntra.com/tshirts/hrx/hrx-men-rust-brown-t-shirt/287176/buy?src=search",
            "http://www.myntra.com/shirts/roadster/roadster-men-green--blue-checked-shelby-slim-fit-casual-shirt/273382/buy?src=search",
            "http://www.myntra.com/jackets/even/even-men-beige-slim-fit-nehru-jacket/324435/buy?src=search",
            "http://www.myntra.com/shorts/adidas/adidas-men-black-shorts/235601/buy?src=search",
            "http://www.myntra.com/jeans/lee/lee-men-light-blue-powell-slim-fit-jeans/310242/buy?src=search",
            "http://www.myntra.com/shirts/roadster/roadster-men-grey--black-checked-slim-fit-casual-shirt/278289/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-navy-blue-t-shirt/267543/buy?src=search",
            "http://www.myntra.com/shorts/roadster/roadster-men-navy--blue-checked-slim-fit-shorts/253304/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-blue-henley-t-shirt/267652/buy?src=search",
            "http://www.myntra.com/briefs/calvin-klein-innerwear/calvin-klein-innerwear-men-black-hip-briefs-u8901d/148749/buy?src=search",
            "http://www.myntra.com/shirts/roadster/roadster-men-blue-alonso-denim-shelby-slim-fit-casual-shirt/254527/buy?src=search",
            "http://www.myntra.com/jeans/hrx/hrx-men-blue-slim-fit-jeans/288259/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-skinny-fit-jeans/262975/buy?src=search",
            "http://www.myntra.com/tshirts/us-polo-assn/us-polo-assn-men-white-polo-t-shirt/318448/buy?src=search",
            "http://www.myntra.com/shirts/united-colors-of-benetton/united-colors-of-benetton-men-blue-casual-shirt/283401/buy?src=search",
            "http://www.myntra.com/shirts/locomotive/locomotive-men-blue--pink-checked-slim-fit-casual-shirt/297905/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-grey-camaro-skinny-fit-jeans/278620/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-corvette-slim-fit-jeans/278643/buy?src=search",
            "http://www.myntra.com/tracksuits/puma/puma-men-black-pe-training-tracksuit/271575/buy?src=search",
            "http://www.myntra.com/trousers/the-indian-garage-co/the-indian-garage-co-men-black-slim-fit-smart-casual-trousers/242023/buy?src=search",
            "http://www.myntra.com/shirts/roadster/roadster-men-white-romain-shelby-slim-fit-casual-shirt/252468/buy?src=search",
            "http://www.myntra.com/shirts/mast--harbour/mast--harbour-men-yellow--off-white-checked-slim-fit-smart-casual-shirt/215953/buy?src=search",
            "http://www.myntra.com/shorts/poe/poe-men-black-cargo-shorts/331181/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-corvette-slim-fit-jeans/248894/buy?src=search",
            "http://www.myntra.com/track-pants/hrx/hrx-men-grey-melange-easy-active-track-pants/262128/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-black-t-shirt/267619/buy?src=search",
            "http://www.myntra.com/tshirts/hrx/hrx-men-white--dark-grey-striped-polo-t-shirt/283494/buy?src=search",
            "http://www.myntra.com/tshirts/adidas/adidas-men-black-polo-t-shirt/166423/buy?src=search",
            "http://www.myntra.com/jeans/lee/lee-men-blue-bruce-skinny-fit-jeans/288071/buy?src=search",
            "http://www.myntra.com/tshirts/cat/cat-men-green-printed-slim-fit-t-shirt/269244/buy?src=search",
            "http://www.myntra.com/jeans/lee/lee-men-blue-bruce-skinny-fit-jeans/310252/buy?src=search",
            "http://www.myntra.com/trousers/roadster/roadster-men-beige-baley-torino-slim-fit-chino-trousers/202896/buy?src=search",
            "http://www.myntra.com/trousers/kook-n-keech/kook-n-keech-men-beige-slim-fit-trousers/273050/buy?src=search",
            "http://www.myntra.com/jeans/sher-singh/sher-singh-men-black-slim-fit-jeans/252355/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-camaro-skinny-fit-jeans/278613/buy?src=search",
            "http://www.myntra.com/shirts/locomotive/locomotive-men-red--navy-checked-slim-fit-casual-shirt/330549/buy?src=search",
            "http://www.myntra.com/tshirts/roadster/roadster-men-grey-polo-t-shirt/220539/buy?src=search",
            "http://www.myntra.com/briefs/punch/punch-men-pink-trunks/318892/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-blue-skinny-fit-jeans/262976/buy?src=search",
            "http://www.myntra.com/tshirts/hrx/hrx-men-black-printed-t-shirt/260613/buy?src=search",
            "http://www.myntra.com/tshirts/roadster/roadster-men-grey-bike-printed-t-shirt/237623/buy?src=search",
            "http://www.myntra.com/jeans/sher-singh/sher-singh-men-charcoal-grey-slim-fit-leather-look-jeans/252357/buy?src=search",
            "http://www.myntra.com/tshirts/freecultr/freecultr-men-black-henley-t-shirt/250438/buy?src=search",
            "http://www.myntra.com/shirts/us-polo-assn/us-polo-assn-men-dark-grey-printed-slim-fit-smart-casual-shirt/318414/buy?src=search",
            "http://www.myntra.com/shirts/united-colors-of-benetton/united-colors-of-benetton-men-navy-checked-casual-shirt/260062/buy?src=search",
            "http://www.myntra.com/shirts/roadster/roadster-men-white--navy-checked-romain-shelby-slim-fit-casual-shirt/279349/buy?src=search",
            "http://www.myntra.com/track-pants/adidas/adidas-men-black-track-pants/281262/buy?src=search",
            "http://www.myntra.com/boxers/etc/etc-men-green-checked-boxers-etcss14bxr-003/256025/buy?src=search",
            "http://www.myntra.com/shirts/hrx/hrx-men-white--navy-slim-fit-casual-shirt/244270/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gristones-men-maroon-t-shirt/267607/buy?src=search",
            "http://www.myntra.com/shirts/us-polo-assn/us-polo-assn-men-black-slim-fit-smart-casual-shirt/318389/buy?src=search",
            "http://www.myntra.com/shirts/hrx/hrx-men-navy-linen-blend-casual-shirt/259378/buy?src=search",
            "http://www.myntra.com/shirts/dazzio/dazzio-men-black-slim-fit-casual-shirt/297603/buy?src=search",
            "http://www.myntra.com/shirts/poe/poe-men-blue-linen-blend-slim-fit-casual-shirt/331154/buy?src=search",
            "http://www.myntra.com/tshirts/united-colors-of-benetton/united-colors-of-benetton-men-green--blue-striped-polo-t-shirt/251291/buy?src=search",
            "http://www.myntra.com/jeans/roadster/roadster-men-indigo-blue-camaro-skinny-fit-jeans/278615/buy?src=search",
            "http://www.myntra.com/shirts/tecza/tecza-men-white--blue-checked-casual-shirt/283048/buy?src=search",
            "http://www.myntra.com/track-pants/nike/nike-men-blue-track-pants/266080/buy?src=search",
            "http://www.myntra.com/boxers/etc/etc-men-magenta-checked-boxers-etcss14bxr-002/256024/buy?src=search",
            "http://www.myntra.com/tshirts/wrangler/wrangler-men-white-machine-printed-t-shirt/258470/buy?src=search",
            "http://www.myntra.com/jeans/united-colors-of-benetton/united-colors-of-benetton-men-blue-carrot-fit-jeans/235295/buy?src=search",
            "http://www.myntra.com/jeans/united-colors-of-benetton/united-colors-of-benetton-men-blue-skinny-fit-jeans/315381/buy?src=search",
            "http://www.myntra.com/tshirts/monteil--munero/monteil--munero-men-red--navy-polo-t-shirt/299177/buy?src=search",
            "http://www.myntra.com/jeans/wrangler/wrangler-men-blue-vegas-skinny-fit-jeans/301820/buy?src=search",
            "http://www.myntra.com/tshirts/kook-n-keech-disney/kook-n-keech-disney-men-blue-printed-t-shirt/282955/buy?src=search",
            "http://www.myntra.com/trousers/roadster/roadster-men-dark-khaki-brent-torino-slim-fit-chino-trousers/211803/buy?src=search",
            "http://www.myntra.com/tshirts/roadster/roadster-men-black-printed-t-shirt/239050/buy?src=search",
            "http://www.myntra.com/shirts/lee/lee-men-blue-printed-slim-fit-casual-shirt/256091/buy?src=search",
            "http://www.myntra.com/tshirts/gritstones/gritstones-men-white-t-shirt/267621/buy?src=search",
            "http://www.myntra.com/tshirts/freecultr/freecultr-men-light-blue-hugo-henley-t-shirt/284253/buy?src=search",
            "http://www.myntra.com/shirts/mast--harbour/mast--harbour-men-charcoal-grey-slim-fit-smart-casual-shirt/210157/buy?src=search",
            "http://www.myntra.com/sweaters/united-colors-of-benetton/united-colors-of-benetton-men-white--blue-ombrey-sweater/235293/buy?src=search"
};

    public static String [] getUrls() { return urls; }
}



